default: &default
  adapter: postgresql
  encoding: unicode
  username:
  password:
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: sqlSimulator_development
test:
  <<: *default
  database: sqlSimulator_test
production:
  <<: *default
  database: sqlSimulator_production
