Hobby.create(name: "野球")
Hobby.create(name: "サッカー")
Hobby.create(name: "読書")


User.create(name: "太郎", birthday: "1991-01-13", hobby_id: 5)
User.create(name: "二郎", birthday: "1992-02-03", hobby_id: 6)
User.create(name: "花子", birthday: "1992-02-03", hobby_id: 5)
User.create(name: "三郎", birthday: "1993-04-03", hobby_id: 7)
User.create(name: "四郎", birthday: "1999-02-02", hobby_id: 4)



Area.create(name: "中央区")
Area.create(name: "新宿区")
Area.create(name: "渋谷区")
Area.create(name: "台東区")
Area.create(name: "港区")
Area.create(name: "墨田区")
Area.create(name: "江戸川区")

Item.create(name: "洗剤", price: 500, genre: "日用品", area_id: 1)
Item.create(name: "ティッシュ", price: 200, genre: "日用品", area_id: 2)
Item.create(name: "チョコレート", price: 80, genre: "食料品", area_id: 3)
Item.create(name: "充電器", price: 2000, genre: "家電", area_id: 4)
Item.create(name: "本", price: 1300, genre: "書籍", area_id: 5)

Item.create(name: "トイレットペーパー", price: 300, genre: "日用品", area_id: 6)
Item.create(name: "カットフルーツ", price: 300, genre: "食料品", area_id: 7)
Item.create(name: "牛乳", price: 200, genre: "食料品", area_id: 2)
Item.create(name: "ドライヤー", price: 1500, genre: "家電", area_id: 3)

Item.create(name: "週刊誌", price: 300, genre: "書籍", area_id: 1)
Item.create(name: "小説", price: 250, genre: "書籍", area_id: 4)

ItemEvaluation.create(item_id: 1, user_id: 5, star: 3.0)
ItemEvaluation.create(item_id: 1, user_id: 1, star: 3.5)
ItemEvaluation.create(item_id: 1, user_id: 2, star: 4.0)
ItemEvaluation.create(item_id: 1, user_id: 3, star: 4.0)
ItemEvaluation.create(item_id: 1, user_id: 4, star: 2.0)
ItemEvaluation.create(item_id: 1, user_id: 6, star: 5.0)

ItemEvaluation.create(item_id: 2, user_id: 5, star: 3.0)
ItemEvaluation.create(item_id: 2, user_id: 1, star: 3.5)
ItemEvaluation.create(item_id: 2, user_id: 3, star: 4.0)
ItemEvaluation.create(item_id: 2, user_id: 4, star: 2.0)

ItemEvaluation.create(item_id: 3, user_id: 5, star: 2.0)
ItemEvaluation.create(item_id: 3, user_id: 1, star: 2.5)
ItemEvaluation.create(item_id: 3, user_id: 2, star: 2.0)
ItemEvaluation.create(item_id: 3, user_id: 3, star: 2.0)
ItemEvaluation.create(item_id: 3, user_id: 4, star: 1.0)
ItemEvaluation.create(item_id: 3, user_id: 6, star: 2.0)

ItemEvaluation.create(item_id: 4, user_id: 5, star: 3.0)
ItemEvaluation.create(item_id: 4, user_id: 1, star: 3.5)
ItemEvaluation.create(item_id: 4, user_id: 4, star: 2.0)
ItemEvaluation.create(item_id: 4, user_id: 6, star: 5.0)

ItemEvaluation.create(item_id: 5, user_id: 5, star: 3.0)
ItemEvaluation.create(item_id: 5, user_id: 1, star: 3.5)
ItemEvaluation.create(item_id: 5, user_id: 4, star: 2.0)
ItemEvaluation.create(item_id: 5, user_id: 6, star: 5.0)

ItemEvaluation.create(item_id: 6, user_id: 5, star: 3.0)
ItemEvaluation.create(item_id: 6, user_id: 1, star: 3.5)
ItemEvaluation.create(item_id: 6, user_id: 4, star: 2.0)
ItemEvaluation.create(item_id: 6, user_id: 6, star: 5.0)

ItemEvaluation.create(item_id: 7, user_id: 5, star: 3.0)
ItemEvaluation.create(item_id: 7, user_id: 1, star: 3.5)
ItemEvaluation.create(item_id: 7, user_id: 4, star: 2.0)
ItemEvaluation.create(item_id: 7, user_id: 6, star: 5.0)

ItemEvaluation.create(item_id: 8, user_id: 5, star: 3.0)
ItemEvaluation.create(item_id: 8, user_id: 1, star: 3.5)
ItemEvaluation.create(item_id: 8, user_id: 4, star: 2.0)
ItemEvaluation.create(item_id: 8, user_id: 6, star: 5.0)
ItemEvaluation.create(item_id: 8, user_id: 5, star: 3.0)
ItemEvaluation.create(item_id: 8, user_id: 1, star: 3.5)
ItemEvaluation.create(item_id: 8, user_id: 4, star: 2.0)
ItemEvaluation.create(item_id: 8, user_id: 6, star: 5.0)


ItemEvaluation.create(item_id: 9, user_id: 5, star: 3.0)
ItemEvaluation.create(item_id: 9, user_id: 1, star: 3.5)
ItemEvaluation.create(item_id: 9, user_id: 4, star: 2.0)
ItemEvaluation.create(item_id: 9, user_id: 6, star: 5.0)

ItemEvaluation.create(item_id: 10, user_id: 5, star: 3.0)
ItemEvaluation.create(item_id: 10, user_id: 1, star: 3.5)
ItemEvaluation.create(item_id: 10, user_id: 4, star: 2.0)
ItemEvaluation.create(item_id: 10, user_id: 6, star: 5.0)

ItemEvaluation.create(item_id: 11, user_id: 5, star: 3.0)
ItemEvaluation.create(item_id: 11, user_id: 1, star: 3.5)
ItemEvaluation.create(item_id: 11, user_id: 4, star: 2.0)
ItemEvaluation.create(item_id: 11, user_id: 6, star: 5.0)

ItemImage.create(item_id: 1, image: "image1")
ItemImage.create(item_id: 2, image: "image2")
ItemImage.create(item_id: 3, image: "image3")
ItemImage.create(item_id: 4, image: "image4")
ItemImage.create(item_id: 5, image: "image5")
ItemImage.create(item_id: 6, image: "image6")
ItemImage.create(item_id: 7, image: "image7")
ItemImage.create(item_id: 8, image: "image8")
ItemImage.create(item_id: 9, image: "image9")
ItemImage.create(item_id: 10, image: "image10")
ItemImage.create(item_id: 11, image: "image11")

# User.create(name: "高橋", birthday: "1992-01-14", hobby_id: 1)
# User.create(name: "佐々木", birthday: "1993-11-20", hobby_id: 2)
# User.create(name: "佐藤", birthday: "1994-02-11", hobby_id: 3)
# User.create(name: "田中", birthday: "1982-04-14", hobby_id: 4)

# Hobby.create(name: "ギター")
# Hobby.create(name: "釣り")
# Hobby.create(name: "ランニング")
# Hobby.create(name: "ゴルフ")
